# Generated by Django 2.1.3 on 2018-11-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=128)),
                ('house_number', models.SmallIntegerField()),
                ('flat_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('email_type', models.SmallIntegerField(choices=[(1, 'prywatny'), (2, 'służbowy')])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('phone_type', models.SmallIntegerField(choices=[(1, 'domowy'), (2, 'służbowy'), (3, 'prywatny')])),
                ('person_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailboxapp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='person_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailboxapp.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailboxapp.Person'),
        ),
    ]
