# Generated by Django 2.1.3 on 2018-11-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxapp', '0005_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testowa',
        ),
    ]
