# Generated by Django 2.1.3 on 2018-11-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxapp', '0006_delete_testowa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
