# Generated by Django 2.1.3 on 2018-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxapp', '0008_auto_20181129_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
